/**
 * @file BabyBotProfiles.ts
 * @description Bot profiles, configurations, and telemetry type definitions.
 * Extracted from BabyBotConsole.tsx for modularity and token hygiene.
 */

export interface BotProfile {
  id: string;
  name: string;
  shortName: string;
  version: string;
  lane: string;
  laneBadge: 'live' | 'shadow' | 'sim';
  asset: string;
  timeframe: string;
  telemetryType: 'dominion' | 'onnx' | 'antipin' | 'scalper' | 'trend' | 'macro_dominion';
  description: string;
  hardCapContracts: number;
  discountCeiling: number;
  playbook: string;
}

export const BOT_PROFILES: Record<string, BotProfile> = {
  'lead_deer_quant': {
    id: 'lead_deer_quant',
    name: 'Lead Deer Quant Trader',
    shortName: 'Lead Deer Quant',
    version: 'v1.0 (Peak & Valley)',
    lane: 'LANE 1 (LIVE REAL-MONEY)',
    laneBadge: 'live',
    asset: 'BTC',
    timeframe: '15m',
    telemetryType: 'macro_dominion',
    description: 'Lead Deer Quant: Dual ONNX Microstructure + Silas TWAP Gravity + Peak & Valley In-Flight Bag Harvester',
    hardCapContracts: 1,
    discountCeiling: 0.52,
    playbook: 'Playbook 2: Drift & 85c Peak Harvester · 35c Valley Salvage · .00 Maker Limit',
  },
  'the_onnx_strategy': {
    id: 'the_onnx_strategy',
    name: 'The ONNX Strategy',
    shortName: 'ONNX Strategy',
    version: 'v1.0 (Quant Dials)',
    lane: 'LANE 2 (SHADOW PAPER)',
    laneBadge: 'shadow',
    asset: 'BTC',
    timeframe: '15m',
    telemetryType: 'onnx',
    description: 'The ONNX Strategy: Dual-Brain Spot Lead vs Kalshi Lag CLOB with 5 Precision Execution Dials',
    hardCapContracts: 1,
    discountCeiling: 0.48,
    playbook: 'Trend Aligned Scalp · Volatility Regime Shield · Sizing Armor',
  },
  'dual_onnx': {
    id: 'dual_onnx',
    name: 'The ONNX Strategy (Dual-Brain)',
    shortName: 'ONNX Strategy',
    version: 'v1.0 (Quant Dials)',
    lane: 'LANE 2 (SHADOW PAPER)',
    laneBadge: 'shadow',
    asset: 'BTC',
    timeframe: '15m',
    telemetryType: 'onnx',
    description: 'The ONNX Strategy: Dual-Brain Spot Lead vs Kalshi Lag CLOB with 5 Precision Execution Dials',
    hardCapContracts: 1,
    discountCeiling: 0.48,
    playbook: 'Trend Aligned Scalp · Volatility Regime Shield · Sizing Armor',
  },
  '3_step_domination_bot': {
    id: '3_step_domination_bot',
    name: '3-Step Dominion v3.2',
    shortName: '3-Step Dom',
    version: 'v3.2',
    lane: 'LANE 1 (LIVE REAL-MONEY)',
    laneBadge: 'live',
    asset: 'BTC',
    timeframe: '15m',
    telemetryType: 'dominion',
    description: 'Original 3-Step Playbook Baseline Engine (Early Breakout, Mid OFI Drift, Late Gamma Snub)',
    hardCapContracts: 1,
    discountCeiling: 0.51,
    playbook: 'Playbook 2: OFI Trend Drift · Resting .51 Limit · Baseline',
  },
  'bot1_v4_domination': {
    id: 'bot1_v4_domination',
    name: 'Bot 1 V4 (Multi-Turnover)',
    shortName: 'Bot 1 V4',
    version: 'v4.0',
    lane: 'LANE 1 (LIVE REAL-MONEY)',
    laneBadge: 'live',
    asset: 'BTC',
    timeframe: '15m',
    telemetryType: 'dominion',
    description: 'Bot 1 Version 4: Multi-Turnover Quantitative Engine (Max 4 Round-Trips/Cycle, 59¢ Floor / 40% Scalp ROI / 45s Timeout)',
    hardCapContracts: 1,
    discountCeiling: 0.59,
    playbook: 'Directional Momentum Scalp · Max 4 Round-Trips · 59¢ Floor / 40% Scalp ROI',
  },
  'macro_onnx': {
    id: 'macro_onnx',
    name: 'ONNX Macro Net v2',
    shortName: 'ONNX Macro v2',
    version: 'v2.4 (Dual-Brain)',
    lane: 'LANE 2 (SHADOW PAPER)',
    laneBadge: 'shadow',
    asset: 'BTC',
    timeframe: '15m',
    telemetryType: 'onnx',
    description: 'Dual-Brain Arbitrage: QuoLas Nano Microscope (Spot) + Built-in Kalshi Microstructure (Binary)',
    hardCapContracts: 1,
    discountCeiling: 0.48,
    playbook: 'Dual-Brain Consensus · Lead-Lag Contradiction Arbitrage',
  },
  'onnx_microstructure_bot': {
    id: 'onnx_microstructure_bot',
    name: 'ONNX Macro Net v2',
    shortName: 'ONNX Macro v2',
    version: 'v2.4 (Dual-Brain)',
    lane: 'LANE 2 (SHADOW PAPER)',
    laneBadge: 'shadow',
    asset: 'BTC',
    timeframe: '15m',
    telemetryType: 'onnx',
    description: 'Dual-Brain Arbitrage: QuoLas Nano Microscope (Spot) + Built-in Kalshi Microstructure (Binary)',
    hardCapContracts: 1,
    discountCeiling: 0.48,
    playbook: 'Dual-Brain Consensus · Lead-Lag Contradiction Arbitrage',
  },
  'dominion_2_bot': {
    id: 'dominion_2_bot',
    name: 'Dominion 2 (Anti-Pin Scalper)',
    shortName: 'Dominion 2',
    version: 'v2.1',
    lane: 'LANE 2 (SHADOW PAPER)',
    laneBadge: 'shadow',
    asset: 'BTC',
    timeframe: '15m',
    telemetryType: 'antipin',
    description: 'Anti-Pin Asymmetric Scalper with Kalshi Tie Exploitation (.25-.42)',
    hardCapContracts: 1,
    discountCeiling: 0.42,
    playbook: 'Anti-Pin Zone Defense · Discount Value Hunter',
  },
  'ofi_sprint_scalper': {
    id: 'ofi_sprint_scalper',
    name: 'OFI Sprint Scalper',
    shortName: 'OFI Scalp',
    version: 'v1.8',
    lane: 'LANE 2 (SHADOW PAPER)',
    laneBadge: 'shadow',
    asset: 'BTC',
    timeframe: '5m',
    telemetryType: 'scalper',
    description: '5-Minute High-Velocity Order Flow Imbalance Momentum Scalper',
    hardCapContracts: 1,
    discountCeiling: 0.50,
    playbook: '5M Velocity Window · T-60s Settlement Freeze',
  },
  'macro_trend_dominion': {
    id: 'macro_trend_dominion',
    name: 'Macro Trend Dominion',
    shortName: 'Macro Trend',
    version: 'v2.0 (3-Brain Fusion)',
    lane: 'LANE 1 (LIVE REAL-MONEY)',
    laneBadge: 'live',
    asset: 'BTC',
    timeframe: '15m',
    telemetryType: 'macro_dominion',
    description: '15M Triple-Brain Consensus (Spot ONNX + Kalshi ONNX + 5m HMM) with 9 Dials & Mistake-Learning Engine',
    hardCapContracts: 1,
    discountCeiling: 0.48,
    playbook: '15M 3-Brain Consensus · 1c–89c Limit Sweetspot · Online Mistake Learning',
  },
  'gold_onnx_bot': {
    id: 'gold_onnx_bot',
    name: 'Gold ONNX Bot (Bot 4)',
    shortName: 'Gold ONNX (B4)',
    version: 'v2.5 (32-D Spacetime)',
    lane: 'LANE 1 (LIVE REAL-MONEY)',
    laneBadge: 'live',
    asset: 'GOLD',
    timeframe: '15m',
    telemetryType: 'macro_dominion',
    description: 'Triple-Brain Gold Sovereign: Binance Spot ONNX + Kalshi Binary ONNX + 5M HMM Regime Fusion',
    hardCapContracts: 1,
    discountCeiling: 0.48,
    playbook: 'Triple-Brain Consensus · Dynamic Volatility Moat · Mistake-Learning Shrinkage',
  },
  'bot5_5min_btc': {
    id: 'bot5_5min_btc',
    name: 'Bot 5 (5-Min BTC)',
    shortName: 'Bot 5 (5M BTC)',
    version: 'v1.0',
    lane: 'LANE 1 (LIVE REAL-MONEY)',
    laneBadge: 'live',
    asset: 'BTC',
    timeframe: '5m',
    telemetryType: 'scalper',
    description: '5-Minute BTC Microstructure Bot. Legitimate Seal of Excellence.',
    hardCapContracts: 1,
    discountCeiling: 0.50,
    playbook: '5M Velocity Window · Verified Seal Active',
  },
};
