"""Standalone Bot Configuration, Constants, and Isolated Per-Asset Profiles."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict
from zoneinfo import ZoneInfo

LOCK_FILE_PATH = Path("data") / "trading_engine.lock"
TEMPLATE_PATH = Path(__file__).resolve().parent.parent / "templates" / "pocket_cockpit.html"
QRCODE_PATH = Path(__file__).resolve().parent.parent / "templates" / "qrcode.min.js"
ET_ZONE = ZoneInfo("America/New_York")

# ---------------------------------------------------------------------------
# Per-Asset Strategy Defaults (Institutional Isolated Profiles)
# ---------------------------------------------------------------------------

DEFAULT_ASSET_PROFILES: Dict[str, Dict[str, Any]] = {
    "BTC": {
        "discount_limit_price": 0.52,
        "momentum_max_price": 0.62,
        "min_confidence": 70.0,
        "min_edge_pct": 6.0,
        "min_ev_dollars": 0.02,
        "min_spot_diff": 35.0,
        "typical_1m_volatility": 14.0,
        "vpin_toxic_threshold": 0.60,
        "take_profit_price_threshold": 0.95,
        "enable_take_profit_ceiling": True,
        "require_reversal_for_tp_ceiling": True,
        "enable_reverse_take_profit_roi": True,
        "reverse_indicator_threshold": 85.0,
        "min_take_profit_roi": 20.0,
        "enable_trailing_ratchet": True,
        "trailing_ratchet_buffer": 0.08,
        "spot_delta_front_run_threshold": 28.0,
        "enable_dynamic_reversal_curve": True,
        "entry_window_open_minutes": 12.0,
        "entry_window_close_minutes": 4.5,
        "twap_immutability_sniper_cents": 0.75,
        "max_queue_depth_ahead": 250,
        "max_clob_spread_cents": 0.05,
        "max_contracts": 1,
    },
    "ETH": {
        "discount_limit_price": 0.52,
        "momentum_max_price": 0.62,
        "min_confidence": 80.0,
        "min_edge_pct": 6.0,
        "min_ev_dollars": 0.02,
        "min_spot_diff": 2.50,
        "typical_1m_volatility": 0.60,
        "vpin_toxic_threshold": 0.60,
        "take_profit_price_threshold": 0.90,
        "enable_take_profit_ceiling": True,
        "require_reversal_for_tp_ceiling": False,
        "enable_reverse_take_profit_roi": True,
        "reverse_indicator_threshold": 85.0,
        "min_take_profit_roi": 20.0,
        "enable_trailing_ratchet": True,
        "trailing_ratchet_buffer": 0.08,
        "spot_delta_front_run_threshold": 2.50,
        "enable_dynamic_reversal_curve": True,
        "entry_window_open_minutes": 12.0,
        "entry_window_close_minutes": 4.5,
        "twap_immutability_sniper_cents": 0.75,
        "max_queue_depth_ahead": 200,
        "max_clob_spread_cents": 0.04,
        "max_contracts": 1,
    },
    "SOL": {
        "discount_limit_price": 0.52,
        "momentum_max_price": 0.60,
        "min_confidence": 82.0,
        "min_edge_pct": 7.0,
        "min_ev_dollars": 0.02,
        "min_spot_diff": 0.50,
        "typical_1m_volatility": 0.04,
        "vpin_toxic_threshold": 0.60,
        "take_profit_price_threshold": 0.90,
        "enable_take_profit_ceiling": True,
        "require_reversal_for_tp_ceiling": False,
        "enable_reverse_take_profit_roi": True,
        "reverse_indicator_threshold": 85.0,
        "min_take_profit_roi": 20.0,
        "enable_trailing_ratchet": True,
        "trailing_ratchet_buffer": 0.08,
        "spot_delta_front_run_threshold": 0.50,
        "enable_dynamic_reversal_curve": True,
        "entry_window_open_minutes": 11.0,
        "entry_window_close_minutes": 3.5,
        "twap_immutability_sniper_cents": 0.72,
        "max_queue_depth_ahead": 150,
        "max_clob_spread_cents": 0.06,
        "max_contracts": 1,
    },
    "DOGE": {
        "discount_limit_price": 0.48,
        "momentum_max_price": 0.55,
        "min_confidence": 84.0,
        "min_edge_pct": 10.0,
        "min_ev_dollars": 0.03,
        "min_spot_diff": 0.0005,
        "typical_1m_volatility": 0.000045,
        "vpin_toxic_threshold": 0.55,
        "take_profit_price_threshold": 0.90,
        "enable_take_profit_ceiling": True,
        "require_reversal_for_tp_ceiling": False,
        "enable_reverse_take_profit_roi": True,
        "reverse_indicator_threshold": 85.0,
        "min_take_profit_roi": 20.0,
        "enable_trailing_ratchet": True,
        "trailing_ratchet_buffer": 0.08,
        "spot_delta_front_run_threshold": 0.0005,
        "enable_dynamic_reversal_curve": True,
        "entry_window_open_minutes": 11.0,
        "entry_window_close_minutes": 3.5,
        "twap_immutability_sniper_cents": 0.70,
        "max_queue_depth_ahead": 300,
        "max_clob_spread_cents": 0.03,
        "max_contracts": 1,
    },
    "GOLD": {
        "discount_limit_price": 0.52,
        "momentum_max_price": 0.52,
        "min_confidence": 80.0,
        "min_edge_pct": 8.0,
        "min_ev_dollars": 0.03,
        "min_spot_diff": 1.50,
        "typical_1m_volatility": 0.75,
        "vpin_toxic_threshold": 0.55,
        "take_profit_price_threshold": 0.92,
        "enable_take_profit_ceiling": True,
        "require_reversal_for_tp_ceiling": False,
        "enable_reverse_take_profit_roi": True,
        "reverse_indicator_threshold": 85.0,
        "min_take_profit_roi": 20.0,
        "enable_trailing_ratchet": True,
        "trailing_ratchet_buffer": 0.08,
        "spot_delta_front_run_threshold": 2.50,
        "enable_dynamic_reversal_curve": True,
        "entry_window_open_minutes": 7.0,
        "entry_window_close_minutes": 2.0,
        "twap_immutability_sniper_cents": 0.75,
        "max_queue_depth_ahead": 150,
        "max_clob_spread_cents": 0.05,
        "max_contracts": 1,
    },
    "HYPER": {
        "discount_limit_price": 0.50,
        "momentum_max_price": 0.58,
        "min_confidence": 82.0,
        "min_edge_pct": 8.0,
        "min_ev_dollars": 0.02,
        "min_spot_diff": 0.35,
        "typical_1m_volatility": 0.08,
        "vpin_toxic_threshold": 0.60,
        "take_profit_price_threshold": 0.90,
        "enable_take_profit_ceiling": True,
        "require_reversal_for_tp_ceiling": False,
        "enable_reverse_take_profit_roi": True,
        "reverse_indicator_threshold": 85.0,
        "min_take_profit_roi": 20.0,
        "enable_trailing_ratchet": True,
        "trailing_ratchet_buffer": 0.08,
        "spot_delta_front_run_threshold": 0.33,
        "enable_dynamic_reversal_curve": True,
        "entry_window_open_minutes": 12.0,
        "entry_window_close_minutes": 4.5,
        "twap_immutability_sniper_cents": 0.72,
        "max_queue_depth_ahead": 200,
        "max_clob_spread_cents": 0.05,
        "max_contracts": 1,
    },
}
